
export class SearchNearByModel {
  siteList: Array<{
    stationID: string, stationName: string, agentName: string, avatar: string, contact: string,
    address: string, lat: string, lng: string, toolTip: string, distance: string, timing: string, isPublic: string,
    pricingType: [], pricing: [], status: string, connectorType: []
  }> = [
      {
        stationID: '',
        stationName: '',
        agentName: '',
        avatar: '',
        contact: '',
        address: '',
        lat: '',
        lng: '',
        toolTip: '',
        distance: '',
        timing: '',
        isPublic: '',
        pricingType: [],
        pricing: [],
        status: '',
        connectorType: []
      },
      {
        stationID: '',
        stationName: '',
        agentName: '',
        avatar: '',
        contact: '',
        address: '',
        lat: '',
        lng: '',
        toolTip: '',
        distance: '',
        timing: '',
        isPublic: '',
        pricingType: [],
        pricing: [],
        status: '',
        connectorType: []
      },
      {
        stationID: '',
        stationName: '',
        agentName: '',
        avatar: '',
        contact: '',
        address: '',
        lat: '',
        lng: '',
        toolTip: '',
        distance: '',
        timing: '',
        isPublic: '',
        pricingType: [],
        pricing: [],
        status: '',
        connectorType: []
      },
      {
        stationID: '',
        stationName: '',
        agentName: '',
        avatar: '',
        contact: '',
        address: '',
        lat: '',
        lng: '',
        toolTip: '',
        distance: '',
        timing: '',
        isPublic: '',
        pricingType: [],
        pricing: [],
        status: '',
        connectorType: []
      },
      {
        stationID: '',
        stationName: '',
        agentName: '',
        avatar: '',
        contact: '',
        address: '',
        lat: '',
        lng: '',
        toolTip: '',
        distance: '',
        timing: '',
        isPublic: '',
        pricingType: [],
        pricing: [],
        status: '',
        connectorType: []
      },
      {
        stationID: '',
        stationName: '',
        agentName: '',
        avatar: '',
        contact: '',
        address: '',
        lat: '',
        lng: '',
        toolTip: '',
        distance: '',
        timing: '',
        isPublic: '',
        pricingType: [],
        pricing: [],
        status: '',
        connectorType: []
      },
      {
        stationID: '',
        stationName: '',
        agentName: '',
        avatar: '',
        contact: '',
        address: '',
        lat: '',
        lng: '',
        toolTip: '',
        distance: '',
        timing: '',
        isPublic: '',
        pricingType: [],
        pricing: [],
        status: '',
        connectorType: []
      },
      {
        stationID: '',
        stationName: '',
        agentName: '',
        avatar: '',
        contact: '',
        address: '',
        lat: '',
        lng: '',
        toolTip: '',
        distance: '',
        timing: '',
        isPublic: '',
        pricingType: [],
        pricing: [],
        status: '',
        connectorType: []
      },
      {
        stationID: '',
        stationName: '',
        agentName: '',
        avatar: '',
        contact: '',
        address: '',
        lat: '',
        lng: '',
        toolTip: '',
        distance: '',
        timing: '',
        isPublic: '',
        pricingType: [],
        pricing: [],
        status: '',
        connectorType: []
      },
      {
        stationID: '',
        stationName: '',
        agentName: '',
        avatar: '',
        contact: '',
        address: '',
        lat: '',
        lng: '',
        toolTip: '',
        distance: '',
        timing: '',
        isPublic: '',
        pricingType: [],
        pricing: [],
        status: '',
        connectorType: []
      },
    ];


  constructor() {
    
  }
}
